#!/bin/bash
# INDI CORE
echo astropi | sudo -S apt-get install -y libnova-dev libcfitsio-dev libusb-1.0-0-dev zlib1g-dev libgsl-dev build-essential cmake git libjpeg-dev libcurl4-gnutls-dev libtiff-dev libfftw3-dev
mkdir -p $HOME/Projects
cd $HOME/Projects
git clone --depth 1 https://github.com/indilib/indi.git
mkdir -p $HOME/Projects/indi-cmake
cd $HOME/Projects/indi-cmake
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug $HOME/Projects/indi
make -j4
echo astropi | sudo -S make install
#
# INDI 3rd PARTY
echo astropi | sudo -S apt-get -y install libnova-dev libcfitsio-dev libusb-1.0-0-dev zlib1g-dev libgsl-dev build-essential cmake git libjpeg-dev libcurl4-gnutls-dev libtiff-dev libfftw3-dev libftdi-dev libgps-dev libraw-dev libdc1394-22-dev libgphoto2-dev libboost-dev libboost-regex-dev librtlsdr-dev liblimesuite-dev libftdi1-dev libavcodec-dev libavdevice-dev
cd $HOME/Projects
git clone --depth=1 https://github.com/indilib/indi-3rdparty
mkdir -p $HOME/Projects/indi3rd-cmake
cd $HOME/Projects/indi3rd-cmake
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug $HOME/Projects/indi-3rdparty/indi-eqmod
make -j4
echo astropi | sudo -S make install
#
# KSTASR ASTROPI
mkdir $HOME/Projects/kstars-cmake
cd $HOME/Projects/kstars-cmake
cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RelWithDebInfo $HOME/.AstroPi-system/kstars
make -j4
echo astropi | sudo -S make install
#
echo astropi | sudo -S rm -rf $HOME/Projects
