#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

export DEBIAN_FRONTEND=noninteractive

apt-get update

REQUIRED_PACKAGES=(
  ca-certificates
  build-essential
  cmake
  git
  pkg-config
  fakeroot
  dpkg-dev
  file
  libeigen3-dev
  libcfitsio-dev
  zlib1g-dev
  libkf5doctools-dev
  libqt5datavisualization5-dev
  extra-cmake-modules
  libkf5plotting-dev
  libqt5svg5-dev
  libkf5xmlgui-dev
  libkf5kio-dev
  kinit-dev
  libkf5newstuff-dev
  libkf5notifications-dev
  qtdeclarative5-dev
  libkf5crash-dev
  gettext
  libnova-dev
  libgsl-dev
  libraw-dev
  libkf5notifyconfig-dev
  wcslib-dev
  libqt5websockets5-dev
  qtkeychain-qt5-dev
  libsecret-1-dev
)

for pkg in "${REQUIRED_PACKAGES[@]}"; do
  apt-get install -y "$pkg"
done

OPTIONAL_PACKAGES=(
  xplanet
  xplanet-images
  breeze-icon-theme
  gsc
  libindi-dev
)

for pkg in "${OPTIONAL_PACKAGES[@]}"; do
  if ! apt-get install -y "$pkg"; then
    echo "[warn] Optional package not available on this base image: $pkg"
  fi
done

mkdir -p build artifacts/rootfs artifacts/deb

cmake -S kstars-astropi -B build \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=/usr \
  -DBUILD_TESTING=Off

cmake --build build -j"$(nproc)"

rm -rf artifacts/rootfs
mkdir -p artifacts/rootfs
DESTDIR="$ROOT_DIR/artifacts/rootfs" cmake --install build

ARCH="armhf"
VERSION="$(grep -E 'set \(KStars_VERSION_(MAJOR|MINOR|REVISION)' kstars-astropi/CMakeLists.txt | awk '{print $3}' | tr -d ')' | paste -sd '.' -)"
PKG_NAME="kstars-astropi-buster"
PKG_DIR="$ROOT_DIR/artifacts/deb/${PKG_NAME}_${VERSION}_${ARCH}"

rm -rf "$PKG_DIR"
mkdir -p "$PKG_DIR/DEBIAN"
cp -a artifacts/rootfs/usr "$PKG_DIR/"

cat > "$PKG_DIR/DEBIAN/control" <<EOF
Package: ${PKG_NAME}
Version: ${VERSION}
Section: science
Priority: optional
Architecture: ${ARCH}
Maintainer: AstroPi System CI <noreply@github.com>
Description: KStars AstroPi build for Raspberry Pi (Buster)
 This package is generated by GitHub Actions and contains binaries
 built for armhf on a Debian/Raspbian Buster-compatible base.
EOF

dpkg-deb --build "$PKG_DIR" "$ROOT_DIR/artifacts/${PKG_NAME}_${VERSION}_${ARCH}.deb"

tar -C "$ROOT_DIR/artifacts/rootfs" -czf "$ROOT_DIR/artifacts/${PKG_NAME}_${VERSION}_${ARCH}_rootfs.tar.gz" .

echo "Build complete. Artifacts:"
ls -lah "$ROOT_DIR/artifacts"
